services:
  linux:
    image: webserv_img
    build:
      context: /absolute/path/to/project
      dockerfile: ./Resources/docker/Dockerfile
    container_name: webserv
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
