#!/usr/bin/env python3

# Define el contenido HTML
html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated HTML</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <p>This is a simple HTML file generated by a Python script.</p>
</body>
</html>
"""

print(html_content)
